name = "PaperCSS"
license = "MIT"
licenselink = "https://github.com/bdcaf/papercss-hugo-theme/blob/master/LICENSE"
description = "A Hugo theme made with PaperCSS, the less formal CSS framework."
homepage = "https://github.com/bdcaf/papercss-hugo-theme"
tags = ["blog", "paper", "informal"]
features = ["blog", "toc", "shortcodes"]
min_version = "0.54.0"

[author]
  name = "Clemens Ager"
  homepage = "https://bdcaf.github.io/"
